### ISSUE TITLE
app in subdirectory

### ISSUE THREAD

**Issue by lesliekimm** [cmaher92/connectall#3]
if you use
```rails new```
instead of
```rails new connectall```
it will create the app within the current directory so we don't have a connectall directory within the connectall repo

@joshuarcher @cmaher92  @mike-kane is this the right way to comment about things on the project amongst the team? anyone know?

**Comment by joshuarcher** [comment]
what Connor did makes sense because we may want to put other files in the connectall folder besides the rails project, that way we can keep everything in the same git repo.

and yes this is a great way to make comments and bring up issues

**Comment by lesliekimm** [comment]
sounds good @joshuarcher
