### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by ajbraus** [cmaher92/ConnectAll#35]
We'll need user feedback for this site, so we need a "contact us" page that sends an email to an admin email address.

**Comment by lesliekimm** [comment]
credentials for this can be found in [docs](https://docs.google.com/a/makegameswith.us/document/d/1dy5-xjmwTJ4Y07VPaF3ZikE34nC_IfCTPq4iq-3tFLM/edit?usp=sharing)

**Comment by lesliekimm** [comment]
open [PR-57](https://github.com/cmaher92/ConnectAll/pull/57)

**Comment by lesliekimm** [comment]
follow up issue - use a contact form with captcha
